### ISSUE TITLE
Select sources that have to be dynamics

### ISSUE THREAD

**Issue by Vinzoof** [running-coder/jquery-typeahead#275]
Thank you for this great plugin :-)
I would like to use the "dynamic" function only for one source. This one has to be refreshed each time the user click the input box and the other (the biggests ones) have to stay in the cache.

Is there a way to do that ? 

Vinzoof

**Comment by running-coder** [comment]
Hey @Vinzoof, it is not possible currently to define dynamic or not per source group. It is a good suggestion and shouldn't be too hard to implement in a future release. Thanks for the suggestion

**Comment by Vinzoof** [comment]
Happy New Year @running-coder and thank you for your answer. 

I'll stay tuned then ! It would be a great improvement for my website's search engine :-) 

To tell you everything, my idea would be to add a source with the user recent history search by using cookies.

**Comment by running-coder** [comment]
Wasn't an easy feature to implement but definitly a cool one! Let me knwo if everything works as expected

**Comment by Vinzoof** [comment]
Hello @running-coder. Thank you really much for your work :-)
I'm sorry but I wasn't successful at getting it to work. How should I implement the dynamic search ?

Here is my code :
`		
testsrc:{
   data: function() {
      if (typeof Cookies.getJSON('search-history') != "undefined") {return Cookies.getJSON('search-history');}
      else {return "";}
   },
   dynamic:true
}`

**Comment by running-coder** [comment]
tested using this init, all works fine it `console.log` on every search. Make sure you have the latest commit on the `develop` branch, I've fixed a bunch of stuff
```
$.typeahead({
    input: '.js-typeahead-input',
    minLength: 1,
    highlight: false,
    emptyTemplate: 'No result for {{query}}',
    source: {
        testsrc:{
            data: function() {
                console.log('coucou');
                return ['data1', 'data2']
            },
            dynamic:true
        }
    }
});
```

**Comment by Vinzoof** [comment]
Thank you @running-coder . I found the source of the malfunction, I had left the cache option to "true".

It seems to be normal when I read your documentation : 
> * This option can't be combined with `dynamic: true,`

However I still can't do what I want to do : have all my sources cached and static (because they are big) and the last one non-cached dynamic (in order to implement an history search).

Don't you think the cache option should also be defined by source ?

++

**Comment by tombertrand** [comment]
created #302 to have proper tracking
