### ISSUE TITLE
XSS issue with emptyTemplate when no results found

### ISSUE THREAD

**Issue by grieblius** [running-coder/jquery-typeahead#355]
Hello,

there is an XSS issue when using `{{query}}` in `emptyTemplate` variable when no results is found.
For example we have such `emptyTemplate`:
`emptyTemplate: 'No result for "{{query}}"',`

If we enter html code in query input , e.g.:  `<img src="" onerror="alert('bad code')">`
the JS code is executed.

In this case `{{query}}` must be treated as plain text, not html code.

Thanks,
Giedrius

**Comment by running-coder** [comment]
Hey @grieblius thanks for raising the issue, this commit should fix the emptyTemplate option

**Comment by kopresh** [comment]
i am still facing this issue. <script>alert(100)</script>. This gives me an alert 100 on empty template content.
